import rateLimitServiceInterceptor from './interceptors/rate-limit-service-logger-interceptor'

export const consumeMagicLinkRequestQuotaService =
  rateLimitServiceInterceptor.consumeMagicLinkRequestQuotaService

export const consumeContactMessageQuotaService =
  rateLimitServiceInterceptor.consumeContactMessageQuotaService

export const purgeExpiredRateLimitFingerprintsService =
  rateLimitServiceInterceptor.purgeExpiredRateLimitFingerprintsService
