import rehypeShiki from '@shikijs/rehype'
import {MDXRemote} from 'next-mdx-remote/rsc'
import remarkGfm from 'remark-gfm'

import {mdxComponents} from './mdx-components'

interface MDXContentProps {
  source: string
}

export async function MDXContent({source}: MDXContentProps) {
  return (
    <article className="w-full max-w-none overflow-x-hidden">
      <MDXRemote
        source={source}
        components={mdxComponents}
        options={{
          mdxOptions: {
            remarkPlugins: [remarkGfm],
            rehypePlugins: [
              [
                rehypeShiki,
                {
                  // Dual-theme : Shiki émet les deux couleurs par token, en
                  // variables CSS (--shiki-light / --shiki-dark), et c'est le
                  // CSS qui tranche. Avant, le thème venait du header x-theme
                  // alors que l'UI suit next-themes : sans cookie, un visiteur
                  // en sombre recevait du code clair sur fond sombre, illisible.
                  // Ça rend aussi la sortie indépendante de la requête, donc
                  // prerenderable — voir D13.
                  themes: {light: 'github-light', dark: 'github-dark'},
                  defaultColor: false,
                  langs: [
                    'javascript',
                    'typescript',
                    'jsx',
                    'tsx',
                    'css',
                    'json',
                    'bash',
                    'html',
                    'markdown',
                    'sql',
                    'ts',
                    'js',
                  ],
                  parseMetaString: (metaString: string) => {
                    const match = metaString.match(/title="([^"]*)"/)
                    return match ? {title: match[1]} : {}
                  },
                  transformers: [
                    {
                      name: 'preserve-language-info',

                      // eslint-disable-next-line @typescript-eslint/no-explicit-any
                      pre(node: {properties: {[x: string]: any}}) {
                        // Preserve language information in data attributes
                        const lang = node.properties.lang
                        if (lang) {
                          node.properties = node.properties || {}
                          node.properties['data-language'] = lang
                        }
                      },
                      code(node: {properties: {[x: string]: string}}) {
                        // Mark code elements generated by Shiki
                        node.properties = node.properties || {}
                        node.properties['data-shiki'] = 'true'
                      },
                    },
                  ],
                },
              ],
            ],
          },
        }}
      />
    </article>
  )
}
