import rehypeShiki from '@shikijs/rehype'
import {connection} from 'next/server'
import {MDXRemote} from 'next-mdx-remote/rsc'
import remarkGfm from 'remark-gfm'

import {mdxComponents} from './mdx-components'

interface MDXContentProps {
  source: string
}

/**
 * Rendu unique du MDX, partagé par la documentation et le blog.
 *
 * La compilation MDX (next-mdx-remote + rehypeShiki) lit l'horloge : elle ne
 * peut pas être prerendue. connection() marque le sous-arbre comme rendu à la
 * requête, ce qui impose aux appelants de l'envelopper d'un <Suspense>.
 */
export async function MDXContent({source}: MDXContentProps) {
  await connection()

  return (
    <div className="prose prose-gray dark:prose-invert prose-headings:text-foreground prose-a:text-link prose-strong:text-foreground prose-code:text-foreground prose-code:before:content-none prose-code:after:content-none prose-pre:bg-transparent prose-pre:p-0 w-full max-w-none overflow-x-hidden">
      <MDXRemote
        source={source}
        components={mdxComponents}
        options={{
          mdxOptions: {
            remarkPlugins: [remarkGfm],
            rehypePlugins: [
              [
                rehypeShiki,
                {
                  themes: {light: 'github-light', dark: 'github-dark'},
                  defaultColor: false,
                  langs: [
                    'javascript',
                    'typescript',
                    'jsx',
                    'tsx',
                    'css',
                    'json',
                    'bash',
                    'html',
                    'markdown',
                    'sql',
                    'ts',
                    'js',
                  ],
                  parseMetaString: (metaString: string) => {
                    const match = metaString.match(/title="([^"]*)"/)
                    return match ? {title: match[1]} : {}
                  },
                  transformers: [
                    {
                      name: 'preserve-language-info',

                      // eslint-disable-next-line @typescript-eslint/no-explicit-any
                      pre(node: {properties: {[x: string]: any}}) {
                        // Preserve language information in data attributes
                        const lang = node.properties.lang
                        if (lang) {
                          node.properties = node.properties || {}
                          node.properties['data-language'] = lang
                        }
                      },
                      code(node: {properties: {[x: string]: string}}) {
                        // Mark code elements generated by Shiki
                        node.properties = node.properties || {}
                        node.properties['data-shiki'] = 'true'
                      },
                    },
                  ],
                },
              ],
            ],
          },
        }}
      />
    </div>
  )
}
