import rehypeShiki from '@shikijs/rehype'
import {MDXRemote} from 'next-mdx-remote/rsc'
import remarkGfm from 'remark-gfm'

import {mdxComponents} from './mdx-components'

interface MDXContentProps {
  source: string
  theme?: string
}

export async function MDXContent({source, theme = 'light'}: MDXContentProps) {
  return (
    <article className="prose prose-sm sm:prose-base lg:prose-lg prose-gray dark:prose-invert prose-headings:text-foreground prose-p:text-muted-foreground prose-a:text-primary prose-strong:text-foreground prose-code:text-foreground prose-pre:bg-muted prose-blockquote:border-l-primary w-full max-w-none overflow-x-hidden">
      <MDXRemote
        source={source}
        components={mdxComponents}
        options={{
          mdxOptions: {
            remarkPlugins: [remarkGfm],
            rehypePlugins: [
              [
                rehypeShiki,
                {
                  theme: theme === 'dark' ? 'github-dark' : 'github-light',
                  langs: [
                    'javascript',
                    'typescript',
                    'jsx',
                    'tsx',
                    'css',
                    'json',
                    'bash',
                    'html',
                    'markdown',
                    'sql',
                    'ts',
                    'js',
                  ],
                  parseMetaString: (metaString: string) => {
                    const match = metaString.match(/title="([^"]*)"/)
                    return match ? {title: match[1]} : {}
                  },
                  transformers: [
                    {
                      name: 'preserve-language-info',

                      // eslint-disable-next-line @typescript-eslint/no-explicit-any
                      pre(node: {properties: {[x: string]: any}}) {
                        // Preserve language information in data attributes
                        const lang = node.properties.lang
                        if (lang) {
                          node.properties = node.properties || {}
                          node.properties['data-language'] = lang
                        }
                      },
                      code(node: {properties: {[x: string]: string}}) {
                        // Mark code elements generated by Shiki
                        node.properties = node.properties || {}
                        node.properties['data-shiki'] = 'true'
                      },
                    },
                  ],
                },
              ],
            ],
          },
        }}
      />
    </article>
  )
}
