
#Get the token here : http://localhost:3000/fr/account (active sessions)
# GET http://localhost:3000/api/projects/by-token
# Authorization: Bearer LhBGvjx4DOjTmVXL1mVNpV5Nzwd4RVxr

#Get the api key here : http://localhost:3000/fr/account/api-keys
# GET http://localhost:3000/api/projects/by-token
# x-api-key:WwGZYxDsbjZMHxeYAUdDAUeVZhXhBkcRHyCJLxgLtaygNtUsiJvQVwosXzvRdKGF

GET http://localhost:3000/api/projects
x-api-key:LKlUTSMGePLSaWmnzbqMEZFMgiDOYspCbAAMfvdRKUNYErlmxFBfHfBuPYAvYIlN

